baseURL: 'https://bloghugo.iannelson.uk/'
languageCode: 'en-gb'
title: 'Ian Nelson'
copyright: ''
theme: 'PaperMod'

enableRobotsTXT: true
enableGitInfo: true
ShowAllPagesInArchive: true

permalinks:
  posts: "/:slug/"

params:
  env: production
  mainSections: ["posts"]
  ShowFullTextinRSS: true
  ShowFooter: true
  footer:
    text: '[FamilyTree](https://familytree.iannelson.uk) · [Archive](archives) · [Categories](categories)'
  homeInfoParams:
    Title: Hi. I’m Ian.
    Content: |
      I write code for a living and words for fun.
      This blog is a dumping ground for thoughts on software architecture, books I pretend I understood, Wordle triumphs, and walks up hills that seemed like a good idea at the time.
      Expect a mix of tech nerdery, midlife musings, and the occasional rant disguised as insight.
      Make of it what you will.

  socialIcons:
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/ianfnelson/'
    - name: 'github'
      url: 'https://github.com/ianfnelson'
    - name: 'instagram'
      url: 'https://www.instagram.com/ianfnelson/'
    - name: 'goodreads'
      url: 'https://www.goodreads.com/user/show/119445213-ian-nelson'
    - name: 'stackoverflow'
      url: 'https://stackoverflow.com/users/2084/ian-nelson'
    - name: 'email'
      url: 'mailto:ian@iannelson.uk'
    - name: 'cv'
      url: 'https://files.iannelson.uk/iannelson.pdf'
    - name: 'rss'
      url: 'https://blog.iannelson.uk/index.xml'

outputs:
  home:
      - HTML
      - RSS

pagination:
  disableAliases: false
  pagerSize: 15

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: Archive
          url: archives
          weight: 1
        - name: Categories
          url: categories
          weight: 3
        - name: Testimonials
          url: testimonials
          weight: 5
        - name: Family Tree
          url: https://familytree.iannelson.uk
          weight: 10