baseURL: 'https://bloghugo.iannelson.uk/'
languageCode: 'en-gb'
title: 'Ian Nelson'
theme: 'PaperMod'
enableGitInfo: true
ShowAllPagesInArchive: true

permalinks:
  posts: "/:slug/"

params:
  mainSections: ["posts"]

pagination:
  disableAliases: false
  pagerSize: 15

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: Testimonials
          url: testimonials
          weight: 1
        - name: Archive
          url: archives
          weight: 3
        - name: Categories
          url: categories
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Email
          url: mailto:ian@iannelson.uk