baseURL: 'https://blog.iannelson.uk/'
languageCode: 'en-gb'
title: 'Ian Nelson'
copyright: ''
theme: 'PaperMod'

enableRobotsTXT: true
enableGitInfo: true
ShowAllPagesInArchive: true

permalinks:
  posts: "/:slug/"

params:
  env: production
  dateFormat: '2 January 2006'
  mainSections: ["posts"]
  ShowFullTextinRSS: true
  ShowFooter: true
  homeInfoParams:
    Title: Between Systems and Sunlight
    Content: |
      Where citizen-scale systems meet the chaos of a three-teenager household.

  socialIcons:
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/ianfnelson/'
    - name: 'github'
      url: 'https://github.com/ianfnelson'
    - name: 'instagram'
      url: 'https://www.instagram.com/ianfnelson/'
    - name: 'goodreads'
      url: 'https://www.goodreads.com/user/show/119445213-ian-nelson'
    - name: 'stackoverflow'
      url: 'https://stackoverflow.com/users/2084/ian-nelson'
    - name: 'email'
      url: 'mailto:ian@iannelson.uk'
    - name: 'rss'
      url: 'https://blog.iannelson.uk/index.xml'

outputs:
  home:
      - HTML
      - RSS

services:
  googleAnalytics:
    id: G-5JMKSPFQKQ

analytics:
  google:
    SiteVerificationTag: 'YqQbqlE8qjFw1Bop9gko46JVdM49Pjv0-_BIWRiTvFM'

pagination:
  disableAliases: false
  pagerSize: 15

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: About
          url: about
          weight: 1
        - name: Testimonials
          url: testimonials
          weight: 2
        - name: Archive
          url: archives
          weight: 3
        - name: Categories
          url: categories
          weight: 4
        - name: Tags
          url: tags
          weight: 5
markup:
  goldmark:
    extensions:
      footnote: true